/* Generated by Yosys 0.59+134 (git sha1 34fa8a4ff, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "addr_gen" *)
(* src = "./demo/demo.v:2.1-21.10" *)
module \$paramod\addr_gen\MAX_DATA=s32'00000000000000000000000100000000 (en, clk, rst, addr);
  (* src = "./demo/demo.v:5.11-5.13" *)
  input en;
  wire en;
  (* src = "./demo/demo.v:5.15-5.18" *)
  input clk;
  wire clk;
  (* src = "./demo/demo.v:5.20-5.23" *)
  input rst;
  wire rst;
  (* src = "./demo/demo.v:6.26-6.30" *)
  output [7:0] addr;
  reg [7:0] addr = 8'h00;
  (* src = "./demo/demo.v:12.2-20.6" *)
  wire [7:0] _0_;
  (* src = "./demo/demo.v:19.13-19.21" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _1_;
  (* src = "./demo/demo.v:16.8-16.32" *)
  wire _2_;
  wire [7:0] _3_;
  assign _1_ = addr + (* src = "./demo/demo.v:19.13-19.21" *) 32'd1;
  assign _2_ = addr == (* src = "./demo/demo.v:16.8-16.32" *) 8'hff;
  (* src = "./demo/demo.v:12.2-20.6" *)
  always @(posedge clk, posedge rst)
    if (rst) addr <= 8'h00;
    else addr <= _0_;
  assign _3_ = _2_ ? (* full_case = 32'd1 *) (* src = "./demo/demo.v:16.8-16.32|./demo/demo.v:16.4-19.22" *) 8'h00 : _1_[7:0];
  assign _0_ = en ? (* src = "./demo/demo.v:15.12-15.14|./demo/demo.v:15.8-20.6" *) _3_ : addr;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "./demo/demo.v:24.1-71.10" *)
module fifo(wen, ren, clk, rst, wdata, rdata, count);
  (* src = "./demo/demo.v:27.11-27.14" *)
  input wen;
  wire wen;
  (* src = "./demo/demo.v:27.16-27.19" *)
  input ren;
  wire ren;
  (* src = "./demo/demo.v:27.21-27.24" *)
  input clk;
  wire clk;
  (* src = "./demo/demo.v:27.26-27.29" *)
  input rst;
  wire rst;
  (* src = "./demo/demo.v:28.14-28.19" *)
  input [7:0] wdata;
  wire [7:0] wdata;
  (* src = "./demo/demo.v:29.19-29.24" *)
  output [7:0] rdata;
  reg [7:0] rdata;
  (* src = "./demo/demo.v:30.24-30.29" *)
  output [8:0] count;
  reg [8:0] count = 9'h000;
  (* src = "./demo/demo.v:36.2-40.5" *)
  wire [7:0] _00_;
  (* src = "./demo/demo.v:36.2-40.5" *)
  wire [7:0] _01_;
  (* src = "./demo/demo.v:36.2-40.5" *)
  wire [7:0] _02_;
  (* src = "./demo/demo.v:62.2-69.5" *)
  wire [8:0] _03_;
  (* src = "./demo/demo.v:36.2-40.5" *)
  wire [7:0] _04_;
  (* src = "./demo/demo.v:66.13-66.22" *)
  (* unused_bits = "9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _05_;
  (* src = "./demo/demo.v:65.12-65.23" *)
  wire _06_;
  (* src = "./demo/demo.v:67.12-67.23" *)
  wire _07_;
  (* src = "./demo/demo.v:65.19-65.23" *)
  wire _08_;
  (* src = "./demo/demo.v:67.19-67.23" *)
  wire _09_;
  wire [8:0] _10_;
  (* src = "./demo/demo.v:68.13-68.22" *)
  (* unused_bits = "9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _11_;
  (* src = "./demo/demo.v:34.27-34.32" *)
  wire [7:0] raddr;
  (* src = "./demo/demo.v:34.20-34.25" *)
  wire [7:0] waddr;
  (* src = "./demo/demo.v:35.12-35.16" *)
  reg [7:0] data [255:0];
  always @(posedge clk) begin
    if (_02_[0])
      data[_00_][0:0] <= _01_[0];
    if (_02_[1])
      data[_00_][1:1] <= _01_[1];
    if (_02_[2])
      data[_00_][2:2] <= _01_[2];
    if (_02_[3])
      data[_00_][3:3] <= _01_[3];
    if (_02_[4])
      data[_00_][4:4] <= _01_[4];
    if (_02_[5])
      data[_00_][5:5] <= _01_[5];
    if (_02_[6])
      data[_00_][6:6] <= _01_[6];
    if (_02_[7])
      data[_00_][7:7] <= _01_[7];
  end
  assign _04_ = data[raddr];
  assign _05_ = count + (* src = "./demo/demo.v:66.13-66.22" *) 32'd1;
  assign _06_ = wen && (* src = "./demo/demo.v:65.12-65.23" *) _08_;
  assign _07_ = ren && (* src = "./demo/demo.v:67.12-67.23" *) _09_;
  assign _08_ = ! (* src = "./demo/demo.v:65.19-65.23" *) ren;
  assign _09_ = ! (* src = "./demo/demo.v:67.19-67.23" *) wen;
  (* src = "./demo/demo.v:62.2-69.5" *)
  always @(posedge clk, posedge rst)
    if (rst) count <= 9'h000;
    else count <= _03_;
  (* src = "./demo/demo.v:36.2-40.5" *)
  always @(posedge clk)
    rdata <= _04_;
  assign _10_ = _07_ ? (* src = "./demo/demo.v:67.12-67.23|./demo/demo.v:67.8-68.23" *) _11_[8:0] : count;
  assign _03_ = _06_ ? (* full_case = 32'd1 *) (* src = "./demo/demo.v:65.12-65.23|./demo/demo.v:65.8-68.23" *) _05_[8:0] : _10_;
  assign _02_ = wen ? (* full_case = 32'd1 *) (* src = "./demo/demo.v:37.7-37.10|./demo/demo.v:37.3-38.25" *) 8'hff : 8'h00;
  assign _01_ = wen ? (* full_case = 32'd1 *) (* src = "./demo/demo.v:37.7-37.10|./demo/demo.v:37.3-38.25" *) wdata : 8'hxx;
  assign _00_ = wen ? (* full_case = 32'd1 *) (* src = "./demo/demo.v:37.7-37.10|./demo/demo.v:37.3-38.25" *) waddr : 8'hxx;
  assign _11_ = count - (* src = "./demo/demo.v:68.13-68.22" *) 32'd1;
  (* src = "./demo/demo.v:52.2-57.3" *)
  \$paramod\addr_gen\MAX_DATA=s32'00000000000000000000000100000000  fifo_reader (
    .addr(raddr),
    .clk(clk),
    .en(ren),
    .rst(rst)
  );
  (* src = "./demo/demo.v:44.2-49.3" *)
  \$paramod\addr_gen\MAX_DATA=s32'00000000000000000000000100000000  fifo_writer (
    .addr(waddr),
    .clk(clk),
    .en(wen),
    .rst(rst)
  );
endmodule
